CREATE TABLE urls (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) UNIQUE NOT NULL,
                      created_at TIMESTAMP NOT NULL
);